package e2b

import (
	"net/http"
	"os"
	"runtime"
	"strings"
	"time"

	"github.com/eric642/e2b-go-sdk/internal/version"
)

// Default request timeout (matches Python/JS SDK).
const (
	DefaultRequestTimeout    = 60 * time.Second
	KeepAlivePingIntervalSec = 50
	KeepAlivePingHeader      = "Keepalive-Ping-Interval"
	DefaultDomain            = "e2b.app"
	envdPort                 = 49983
	defaultUser              = "user"
)

// SDKVersion is this SDK's release version. It is kept in lockstep with the
// upstream python-sdk tag (see spec/E2B_VERSION) and regenerated by
// scripts/sync-spec.sh.
const SDKVersion = version.SDKVersion

// UpstreamTag identifies the E2B git tag whose spec was used to generate
// the REST/Connect-RPC clients in internal/.
const UpstreamTag = version.UpstreamTag

// Config holds connection/auth/transport settings shared by all client calls.
// It mirrors Python's ConnectionConfig and JS's ConnectionOpts.
//
// A zero Config is valid — missing fields fall back to environment variables
// (E2B_API_KEY, E2B_DOMAIN, E2B_ACCESS_TOKEN, E2B_API_URL, E2B_SANDBOX_URL,
// E2B_DEBUG) and then to sensible defaults.
type Config struct {
	// APIKey authenticates team-scoped requests (X-API-Key header).
	// Defaults to $E2B_API_KEY.
	APIKey string

	// AccessToken authenticates user-scoped requests (Authorization: Bearer).
	// Defaults to $E2B_ACCESS_TOKEN.
	AccessToken string

	// Domain for sandbox URLs and the default API URL. Defaults to $E2B_DOMAIN
	// or "e2b.app".
	Domain string

	// APIURL overrides the control-plane URL. Defaults to https://api.<domain>
	// (or http://localhost:3000 when Debug is true).
	APIURL string

	// SandboxURL overrides the envd URL per-sandbox (testing/tunneling).
	// Defaults to $E2B_SANDBOX_URL.
	SandboxURL string

	// Debug flips the default API URL to localhost and sandbox URLs to http://.
	// Defaults to $E2B_DEBUG == "true".
	Debug bool

	// RequestTimeout bounds a single HTTP request. 0 means "no timeout".
	// When unset (zero Duration) the SDK uses DefaultRequestTimeout; callers
	// can disable it by setting Config.RequestTimeoutDisabled = true.
	RequestTimeout         time.Duration
	RequestTimeoutDisabled bool

	// Headers added to every REST request (additional sandbox headers are
	// applied on envd traffic too).
	Headers map[string]string

	// ExtraSandboxHeaders added only to envd traffic.
	ExtraSandboxHeaders map[string]string

	// HTTPClient optionally overrides the transport. If nil a default client
	// with RequestTimeout is built on demand.
	HTTPClient *http.Client
}

// resolve returns a copy with env-var fallbacks and defaults applied.
func (c Config) resolve() Config {
	out := c
	if out.Domain == "" {
		if v := os.Getenv("E2B_DOMAIN"); v != "" {
			out.Domain = v
		} else {
			out.Domain = DefaultDomain
		}
	}
	if out.APIKey == "" {
		out.APIKey = os.Getenv("E2B_API_KEY")
	}
	if out.AccessToken == "" {
		out.AccessToken = os.Getenv("E2B_ACCESS_TOKEN")
	}
	if !out.Debug {
		out.Debug = strings.EqualFold(os.Getenv("E2B_DEBUG"), "true")
	}
	if out.APIURL == "" {
		if v := os.Getenv("E2B_API_URL"); v != "" {
			out.APIURL = v
		} else if out.Debug {
			out.APIURL = "http://localhost:3000"
		} else {
			out.APIURL = "https://api." + out.Domain
		}
	}
	if out.SandboxURL == "" {
		out.SandboxURL = os.Getenv("E2B_SANDBOX_URL")
	}
	if out.RequestTimeout == 0 && !out.RequestTimeoutDisabled {
		out.RequestTimeout = DefaultRequestTimeout
	}
	if out.Headers == nil {
		out.Headers = map[string]string{}
	}
	if _, ok := out.Headers["User-Agent"]; !ok {
		out.Headers["User-Agent"] = userAgent()
	}
	return out
}

func userAgent() string {
	return "e2b-go-sdk/" + SDKVersion + " (" + runtime.GOOS + "/" + runtime.GOARCH + ")"
}

// sandboxURL returns the base URL of envd for the given sandbox.
func (c Config) sandboxURL(sandboxID, sandboxDomain string) string {
	if c.SandboxURL != "" {
		return c.SandboxURL
	}
	scheme := "https"
	if c.Debug {
		scheme = "http"
	}
	return scheme + "://" + c.sandboxHost(sandboxID, sandboxDomain, envdPort)
}

// sandboxHost returns host:port to reach a given sandbox port externally.
func (c Config) sandboxHost(sandboxID, sandboxDomain string, port int) string {
	if c.Debug {
		return "localhost:" + itoa(port)
	}
	if sandboxDomain == "" {
		sandboxDomain = c.Domain
	}
	return itoa(port) + "-" + sandboxID + "." + sandboxDomain
}

// httpClient returns the HTTP client for this config, constructing a default
// one with the configured RequestTimeout when none is provided.
func (c Config) httpClient() *http.Client {
	if c.HTTPClient != nil {
		return c.HTTPClient
	}
	return &http.Client{Timeout: c.RequestTimeout}
}

// Resolve returns a Config copy with environment-variable fallbacks and
// defaults applied. Safe to call on a zero Config.
func (c Config) Resolve() Config { return c.resolve() }

// ResolvedHTTPClient returns the HTTP client this Config would use: the
// HTTPClient field if set, else a fresh *http.Client with RequestTimeout.
// Named with the Resolved- prefix because it would otherwise collide with
// the HTTPClient struct field.
func (c Config) ResolvedHTTPClient() *http.Client { return c.httpClient() }

// itoa avoids strconv dependency for hot paths.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
