// Code generated by scripts/sync-spec.sh. DO NOT EDIT.
package version

// UpstreamTag is the git tag in e2b-dev/E2B whose spec generated this SDK.
const UpstreamTag = "a6a1156a76753d5e9bbdd9eb7b26e84aa18b24d2"

// UpstreamSemver is the semver portion of UpstreamTag (e.g. "2.20.0").
const UpstreamSemver = "0.0.0-dev+a6a1156a7675"

// UpstreamCommit is the resolved E2B submodule commit.
const UpstreamCommit = "a6a1156a76753d5e9bbdd9eb7b26e84aa18b24d2"

// SDKVersion is this Go SDK's release version. Pre-alignment releases use
// the v0.x line; once we cut a release directly from an upstream `e2b@X.Y.Z`
// tag we'll switch to matching it 1:1.
const SDKVersion = "0.1.0"
