#!/usr/bin/env bash
# Sync E2B specs from the upstream submodule at a specific tag, then
# regenerate client code.
#
# Usage:
#   scripts/sync-spec.sh                         # sync to latest python-sdk tag
#   scripts/sync-spec.sh python-sdk@2.20.0       # sync to explicit tag
#   scripts/sync-spec.sh --ref main              # sync to a branch ref
#   scripts/sync-spec.sh --skip-fetch            # don't hit the network
#
# Environment:
#   FETCH_TIMEOUT   seconds to wait for `git fetch` (default 60)
#
# The script:
#   1. Ensures the E2B submodule is initialized
#   2. Fetches tags and resolves the target ref (unless --skip-fetch)
#   3. Checks out the submodule at that ref (detached HEAD)
#   4. Copies spec files into ./spec/
#   5. Writes spec/E2B_VERSION and internal/version/upstream.go
#   6. Updates VERSION to match the upstream tag's semver

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SUBMODULE_DIR="$REPO_ROOT/E2B"
SPEC_DIR="$REPO_ROOT/spec"
VERSION_PKG="$REPO_ROOT/internal/version"
VERSION_FILE="$REPO_ROOT/VERSION"

log() { printf '==> %s\n' "$*" >&2; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

# --- arg parsing -------------------------------------------------------------

TAG=""
USE_REF=false
SKIP_FETCH=false
FETCH_TIMEOUT="${FETCH_TIMEOUT:-60}"
while (( $# )); do
  case "$1" in
    --ref)        USE_REF=true; TAG="${2:-}"; shift 2 ;;
    --skip-fetch) SKIP_FETCH=true; shift ;;
    -h|--help)
      sed -n '2,/^set -euo/p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    --) shift; break ;;
    -*) die "unknown flag: $1" ;;
    *)  TAG="$1"; shift ;;
  esac
done

# --- preconditions -----------------------------------------------------------

[[ -d "$SUBMODULE_DIR/.git" || -f "$SUBMODULE_DIR/.git" ]] || {
  log "initializing submodule"
  git -C "$REPO_ROOT" submodule update --init --recursive
}

if $SKIP_FETCH; then
  log "--skip-fetch: using existing local refs"
else
  log "fetching upstream tags (timeout ${FETCH_TIMEOUT}s)"
  if command -v timeout >/dev/null 2>&1; then
    timeout "${FETCH_TIMEOUT}" git -C "$SUBMODULE_DIR" fetch --tags --force origin >/dev/null 2>&1 \
      || log "warning: fetch timed out or failed; continuing with local tags"
  else
    git -C "$SUBMODULE_DIR" fetch --tags --force origin >/dev/null 2>&1 \
      || log "warning: fetch failed; continuing with local tags"
  fi
fi

# --- resolve target ----------------------------------------------------------

if [[ -z "$TAG" ]]; then
  # Pick the newest python-sdk tag by version sort.
  TAG="$(git -C "$SUBMODULE_DIR" tag --list 'python-sdk@*' --sort=-v:refname | head -n1)"
  [[ -n "$TAG" ]] || die "no python-sdk@* tags found; pass one explicitly"
  log "latest upstream tag: $TAG"
fi

if $USE_REF; then
  RESOLVED="$TAG"
else
  git -C "$SUBMODULE_DIR" rev-parse -q --verify "refs/tags/$TAG" >/dev/null || {
    die "tag not found: $TAG (run: git -C E2B tag --list 'python-sdk@*')"
  }
  RESOLVED="refs/tags/$TAG"
fi

log "checking out E2B at $RESOLVED"
git -C "$SUBMODULE_DIR" checkout --quiet --detach "$RESOLVED"
SUBMODULE_SHA="$(git -C "$SUBMODULE_DIR" rev-parse HEAD)"

# --- derive semver -----------------------------------------------------------
# Upstream tags look like "python-sdk@2.20.0"; strip the prefix.
# For non-tag refs we produce a pseudo-semver "0.0.0-dev+<short-sha>" so the
# Go module can still be built, but it's obvious the checkout is unreleased.
if [[ "$TAG" == *"@"* ]]; then
  SEMVER="${TAG##*@}"
elif [[ "$TAG" =~ ^[0-9]+\.[0-9]+ ]]; then
  SEMVER="$TAG"
else
  SEMVER="0.0.0-dev+${SUBMODULE_SHA:0:12}"
fi

# --- copy specs --------------------------------------------------------------

log "copying specs into $SPEC_DIR"
mkdir -p "$SPEC_DIR/envd/process" "$SPEC_DIR/envd/filesystem"
cp "$SUBMODULE_DIR/spec/openapi.yml"                  "$SPEC_DIR/openapi.yml"
cp "$SUBMODULE_DIR/spec/openapi-volumecontent.yml"    "$SPEC_DIR/openapi-volumecontent.yml"
cp "$SUBMODULE_DIR/spec/envd/envd.yaml"               "$SPEC_DIR/envd/envd.yaml"
cp "$SUBMODULE_DIR/spec/envd/process/process.proto"   "$SPEC_DIR/envd/process/process.proto"
cp "$SUBMODULE_DIR/spec/envd/filesystem/filesystem.proto" "$SPEC_DIR/envd/filesystem/filesystem.proto"

# --- pin the version ---------------------------------------------------------

log "pinning spec/E2B_VERSION to $TAG"
cat > "$SPEC_DIR/E2B_VERSION" <<EOF
# Upstream E2B spec source of truth. Managed by scripts/sync-spec.sh.
# Do not edit by hand.
tag=$TAG
semver=$SEMVER
commit=$SUBMODULE_SHA
EOF

log "writing VERSION to $SEMVER"
echo "$SEMVER" > "$VERSION_FILE"

mkdir -p "$VERSION_PKG"
cat > "$VERSION_PKG/upstream.go" <<EOF
// Code generated by scripts/sync-spec.sh. DO NOT EDIT.
package version

// UpstreamTag is the git tag in e2b-dev/E2B whose spec generated this SDK.
const UpstreamTag = "$TAG"

// UpstreamSemver is the semver portion of UpstreamTag (e.g. "2.20.0").
const UpstreamSemver = "$SEMVER"

// UpstreamCommit is the resolved E2B submodule commit.
const UpstreamCommit = "$SUBMODULE_SHA"

// SDKVersion is this Go SDK's release version; kept in lockstep with the
// upstream python-sdk semver.
const SDKVersion = "$SEMVER"
EOF

log "done. Next: run 'make codegen' to regenerate clients"
