// Package volumeapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package volumeapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	VolumeJWTScopes = "VolumeJWT.Scopes"
)

// Defines values for VolumeEntryStatType.
const (
	Directory VolumeEntryStatType = "directory"
	File      VolumeEntryStatType = "file"
	Symlink   VolumeEntryStatType = "symlink"
	Unknown   VolumeEntryStatType = "unknown"
)

// Valid indicates whether the value is a known member of the VolumeEntryStatType enum.
func (e VolumeEntryStatType) Valid() bool {
	switch e {
	case Directory:
		return true
	case File:
		return true
	case Symlink:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code string `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// VolumeDirectoryListing defines model for VolumeDirectoryListing.
type VolumeDirectoryListing = []VolumeEntryStat

// VolumeEntryStat defines model for VolumeEntryStat.
type VolumeEntryStat struct {
	Atime  time.Time           `json:"atime"`
	Ctime  time.Time           `json:"ctime"`
	Gid    uint32              `json:"gid"`
	Mode   uint32              `json:"mode"`
	Mtime  time.Time           `json:"mtime"`
	Name   string              `json:"name"`
	Path   string              `json:"path"`
	Size   int64               `json:"size"`
	Target *string             `json:"target,omitempty"`
	Type   VolumeEntryStatType `json:"type"`
	Uid    uint32              `json:"uid"`
}

// VolumeEntryStatType defines model for VolumeEntryStat.Type.
type VolumeEntryStatType string

// Path defines model for path.
type Path = string

// VolumeID defines model for volumeID.
type VolumeID = string

// N400 defines model for 400.
type N400 = Error

// N401 defines model for 401.
type N401 = Error

// N403 defines model for 403.
type N403 = Error

// N404 defines model for 404.
type N404 = Error

// N409 defines model for 409.
type N409 = Error

// N500 defines model for 500.
type N500 = Error

// GetVolumecontentVolumeIDDirParams defines parameters for GetVolumecontentVolumeIDDir.
type GetVolumecontentVolumeIDDirParams struct {
	Path Path `form:"path" json:"path"`

	// Depth Number of layers deep to recurse into the directory
	Depth *uint32 `form:"depth,omitempty" json:"depth,omitempty"`
}

// PostVolumecontentVolumeIDDirParams defines parameters for PostVolumecontentVolumeIDDir.
type PostVolumecontentVolumeIDDirParams struct {
	Path Path `form:"path" json:"path"`

	// Uid User ID of the created directory
	Uid *uint32 `form:"uid,omitempty" json:"uid,omitempty"`

	// Gid Group ID of the created directory
	Gid *uint32 `form:"gid,omitempty" json:"gid,omitempty"`

	// Mode Mode of the created directory
	Mode *uint32 `form:"mode,omitempty" json:"mode,omitempty"`

	// Force Create the parents of a directory if they don't exist
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// GetVolumecontentVolumeIDFileParams defines parameters for GetVolumecontentVolumeIDFile.
type GetVolumecontentVolumeIDFileParams struct {
	Path Path `form:"path" json:"path"`
}

// PutVolumecontentVolumeIDFileParams defines parameters for PutVolumecontentVolumeIDFile.
type PutVolumecontentVolumeIDFileParams struct {
	Path Path `form:"path" json:"path"`

	// Uid User ID of the uploaded file
	Uid *uint32 `form:"uid,omitempty" json:"uid,omitempty"`

	// Gid Group ID of the uploaded file
	Gid *uint32 `form:"gid,omitempty" json:"gid,omitempty"`

	// Mode Mode of the uploaded file
	Mode *uint32 `form:"mode,omitempty" json:"mode,omitempty"`

	// Force Force overwrite of an existing file
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// DeleteVolumecontentVolumeIDPathParams defines parameters for DeleteVolumecontentVolumeIDPath.
type DeleteVolumecontentVolumeIDPathParams struct {
	Path Path `form:"path" json:"path"`
}

// GetVolumecontentVolumeIDPathParams defines parameters for GetVolumecontentVolumeIDPath.
type GetVolumecontentVolumeIDPathParams struct {
	Path Path `form:"path" json:"path"`
}

// PatchVolumecontentVolumeIDPathJSONBody defines parameters for PatchVolumecontentVolumeIDPath.
type PatchVolumecontentVolumeIDPathJSONBody struct {
	Gid  *uint32 `json:"gid,omitempty"`
	Mode *uint32 `json:"mode,omitempty"`
	Uid  *uint32 `json:"uid,omitempty"`
}

// PatchVolumecontentVolumeIDPathParams defines parameters for PatchVolumecontentVolumeIDPath.
type PatchVolumecontentVolumeIDPathParams struct {
	Path Path `form:"path" json:"path"`
}

// PatchVolumecontentVolumeIDPathJSONRequestBody defines body for PatchVolumecontentVolumeIDPath for application/json ContentType.
type PatchVolumecontentVolumeIDPathJSONRequestBody PatchVolumecontentVolumeIDPathJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetVolumecontentVolumeIDDir request
	GetVolumecontentVolumeIDDir(ctx context.Context, volumeID VolumeID, params *GetVolumecontentVolumeIDDirParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostVolumecontentVolumeIDDir request
	PostVolumecontentVolumeIDDir(ctx context.Context, volumeID VolumeID, params *PostVolumecontentVolumeIDDirParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVolumecontentVolumeIDFile request
	GetVolumecontentVolumeIDFile(ctx context.Context, volumeID VolumeID, params *GetVolumecontentVolumeIDFileParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutVolumecontentVolumeIDFileWithBody request with any body
	PutVolumecontentVolumeIDFileWithBody(ctx context.Context, volumeID VolumeID, params *PutVolumecontentVolumeIDFileParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteVolumecontentVolumeIDPath request
	DeleteVolumecontentVolumeIDPath(ctx context.Context, volumeID VolumeID, params *DeleteVolumecontentVolumeIDPathParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVolumecontentVolumeIDPath request
	GetVolumecontentVolumeIDPath(ctx context.Context, volumeID VolumeID, params *GetVolumecontentVolumeIDPathParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchVolumecontentVolumeIDPathWithBody request with any body
	PatchVolumecontentVolumeIDPathWithBody(ctx context.Context, volumeID VolumeID, params *PatchVolumecontentVolumeIDPathParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchVolumecontentVolumeIDPath(ctx context.Context, volumeID VolumeID, params *PatchVolumecontentVolumeIDPathParams, body PatchVolumecontentVolumeIDPathJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetVolumecontentVolumeIDDir(ctx context.Context, volumeID VolumeID, params *GetVolumecontentVolumeIDDirParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVolumecontentVolumeIDDirRequest(c.Server, volumeID, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostVolumecontentVolumeIDDir(ctx context.Context, volumeID VolumeID, params *PostVolumecontentVolumeIDDirParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostVolumecontentVolumeIDDirRequest(c.Server, volumeID, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVolumecontentVolumeIDFile(ctx context.Context, volumeID VolumeID, params *GetVolumecontentVolumeIDFileParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVolumecontentVolumeIDFileRequest(c.Server, volumeID, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutVolumecontentVolumeIDFileWithBody(ctx context.Context, volumeID VolumeID, params *PutVolumecontentVolumeIDFileParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutVolumecontentVolumeIDFileRequestWithBody(c.Server, volumeID, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteVolumecontentVolumeIDPath(ctx context.Context, volumeID VolumeID, params *DeleteVolumecontentVolumeIDPathParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteVolumecontentVolumeIDPathRequest(c.Server, volumeID, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVolumecontentVolumeIDPath(ctx context.Context, volumeID VolumeID, params *GetVolumecontentVolumeIDPathParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVolumecontentVolumeIDPathRequest(c.Server, volumeID, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchVolumecontentVolumeIDPathWithBody(ctx context.Context, volumeID VolumeID, params *PatchVolumecontentVolumeIDPathParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchVolumecontentVolumeIDPathRequestWithBody(c.Server, volumeID, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchVolumecontentVolumeIDPath(ctx context.Context, volumeID VolumeID, params *PatchVolumecontentVolumeIDPathParams, body PatchVolumecontentVolumeIDPathJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchVolumecontentVolumeIDPathRequest(c.Server, volumeID, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetVolumecontentVolumeIDDirRequest generates requests for GetVolumecontentVolumeIDDir
func NewGetVolumecontentVolumeIDDirRequest(server string, volumeID VolumeID, params *GetVolumecontentVolumeIDDirParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "volumeID", volumeID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/volumecontent/%s/dir", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "path", params.Path, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Depth != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "depth", *params.Depth, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "uint32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostVolumecontentVolumeIDDirRequest generates requests for PostVolumecontentVolumeIDDir
func NewPostVolumecontentVolumeIDDirRequest(server string, volumeID VolumeID, params *PostVolumecontentVolumeIDDirParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "volumeID", volumeID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/volumecontent/%s/dir", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "path", params.Path, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Uid != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "uid", *params.Uid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "uint32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Gid != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "gid", *params.Gid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "uint32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Mode != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "mode", *params.Mode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "uint32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Force != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "force", *params.Force, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetVolumecontentVolumeIDFileRequest generates requests for GetVolumecontentVolumeIDFile
func NewGetVolumecontentVolumeIDFileRequest(server string, volumeID VolumeID, params *GetVolumecontentVolumeIDFileParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "volumeID", volumeID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/volumecontent/%s/file", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "path", params.Path, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutVolumecontentVolumeIDFileRequestWithBody generates requests for PutVolumecontentVolumeIDFile with any type of body
func NewPutVolumecontentVolumeIDFileRequestWithBody(server string, volumeID VolumeID, params *PutVolumecontentVolumeIDFileParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "volumeID", volumeID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/volumecontent/%s/file", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "path", params.Path, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Uid != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "uid", *params.Uid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "uint32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Gid != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "gid", *params.Gid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "uint32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Mode != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "mode", *params.Mode, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "uint32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Force != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "force", *params.Force, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteVolumecontentVolumeIDPathRequest generates requests for DeleteVolumecontentVolumeIDPath
func NewDeleteVolumecontentVolumeIDPathRequest(server string, volumeID VolumeID, params *DeleteVolumecontentVolumeIDPathParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "volumeID", volumeID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/volumecontent/%s/path", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "path", params.Path, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetVolumecontentVolumeIDPathRequest generates requests for GetVolumecontentVolumeIDPath
func NewGetVolumecontentVolumeIDPathRequest(server string, volumeID VolumeID, params *GetVolumecontentVolumeIDPathParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "volumeID", volumeID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/volumecontent/%s/path", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "path", params.Path, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchVolumecontentVolumeIDPathRequest calls the generic PatchVolumecontentVolumeIDPath builder with application/json body
func NewPatchVolumecontentVolumeIDPathRequest(server string, volumeID VolumeID, params *PatchVolumecontentVolumeIDPathParams, body PatchVolumecontentVolumeIDPathJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchVolumecontentVolumeIDPathRequestWithBody(server, volumeID, params, "application/json", bodyReader)
}

// NewPatchVolumecontentVolumeIDPathRequestWithBody generates requests for PatchVolumecontentVolumeIDPath with any type of body
func NewPatchVolumecontentVolumeIDPathRequestWithBody(server string, volumeID VolumeID, params *PatchVolumecontentVolumeIDPathParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "volumeID", volumeID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/volumecontent/%s/path", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "path", params.Path, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetVolumecontentVolumeIDDirWithResponse request
	GetVolumecontentVolumeIDDirWithResponse(ctx context.Context, volumeID VolumeID, params *GetVolumecontentVolumeIDDirParams, reqEditors ...RequestEditorFn) (*GetVolumecontentVolumeIDDirResponse, error)

	// PostVolumecontentVolumeIDDirWithResponse request
	PostVolumecontentVolumeIDDirWithResponse(ctx context.Context, volumeID VolumeID, params *PostVolumecontentVolumeIDDirParams, reqEditors ...RequestEditorFn) (*PostVolumecontentVolumeIDDirResponse, error)

	// GetVolumecontentVolumeIDFileWithResponse request
	GetVolumecontentVolumeIDFileWithResponse(ctx context.Context, volumeID VolumeID, params *GetVolumecontentVolumeIDFileParams, reqEditors ...RequestEditorFn) (*GetVolumecontentVolumeIDFileResponse, error)

	// PutVolumecontentVolumeIDFileWithBodyWithResponse request with any body
	PutVolumecontentVolumeIDFileWithBodyWithResponse(ctx context.Context, volumeID VolumeID, params *PutVolumecontentVolumeIDFileParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutVolumecontentVolumeIDFileResponse, error)

	// DeleteVolumecontentVolumeIDPathWithResponse request
	DeleteVolumecontentVolumeIDPathWithResponse(ctx context.Context, volumeID VolumeID, params *DeleteVolumecontentVolumeIDPathParams, reqEditors ...RequestEditorFn) (*DeleteVolumecontentVolumeIDPathResponse, error)

	// GetVolumecontentVolumeIDPathWithResponse request
	GetVolumecontentVolumeIDPathWithResponse(ctx context.Context, volumeID VolumeID, params *GetVolumecontentVolumeIDPathParams, reqEditors ...RequestEditorFn) (*GetVolumecontentVolumeIDPathResponse, error)

	// PatchVolumecontentVolumeIDPathWithBodyWithResponse request with any body
	PatchVolumecontentVolumeIDPathWithBodyWithResponse(ctx context.Context, volumeID VolumeID, params *PatchVolumecontentVolumeIDPathParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchVolumecontentVolumeIDPathResponse, error)

	PatchVolumecontentVolumeIDPathWithResponse(ctx context.Context, volumeID VolumeID, params *PatchVolumecontentVolumeIDPathParams, body PatchVolumecontentVolumeIDPathJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchVolumecontentVolumeIDPathResponse, error)
}

type GetVolumecontentVolumeIDDirResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VolumeDirectoryListing
	JSON500      *N500
}

// Status returns HTTPResponse.Status
func (r GetVolumecontentVolumeIDDirResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVolumecontentVolumeIDDirResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostVolumecontentVolumeIDDirResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *VolumeEntryStat
	JSON500      *N500
}

// Status returns HTTPResponse.Status
func (r PostVolumecontentVolumeIDDirResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostVolumecontentVolumeIDDirResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetVolumecontentVolumeIDFileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON500      *N500
}

// Status returns HTTPResponse.Status
func (r GetVolumecontentVolumeIDFileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVolumecontentVolumeIDFileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutVolumecontentVolumeIDFileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *VolumeEntryStat
	JSON500      *N500
}

// Status returns HTTPResponse.Status
func (r PutVolumecontentVolumeIDFileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutVolumecontentVolumeIDFileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteVolumecontentVolumeIDPathResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *N404
}

// Status returns HTTPResponse.Status
func (r DeleteVolumecontentVolumeIDPathResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteVolumecontentVolumeIDPathResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetVolumecontentVolumeIDPathResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VolumeEntryStat
	JSON404      *N404
}

// Status returns HTTPResponse.Status
func (r GetVolumecontentVolumeIDPathResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVolumecontentVolumeIDPathResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchVolumecontentVolumeIDPathResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VolumeEntryStat
}

// Status returns HTTPResponse.Status
func (r PatchVolumecontentVolumeIDPathResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchVolumecontentVolumeIDPathResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetVolumecontentVolumeIDDirWithResponse request returning *GetVolumecontentVolumeIDDirResponse
func (c *ClientWithResponses) GetVolumecontentVolumeIDDirWithResponse(ctx context.Context, volumeID VolumeID, params *GetVolumecontentVolumeIDDirParams, reqEditors ...RequestEditorFn) (*GetVolumecontentVolumeIDDirResponse, error) {
	rsp, err := c.GetVolumecontentVolumeIDDir(ctx, volumeID, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVolumecontentVolumeIDDirResponse(rsp)
}

// PostVolumecontentVolumeIDDirWithResponse request returning *PostVolumecontentVolumeIDDirResponse
func (c *ClientWithResponses) PostVolumecontentVolumeIDDirWithResponse(ctx context.Context, volumeID VolumeID, params *PostVolumecontentVolumeIDDirParams, reqEditors ...RequestEditorFn) (*PostVolumecontentVolumeIDDirResponse, error) {
	rsp, err := c.PostVolumecontentVolumeIDDir(ctx, volumeID, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostVolumecontentVolumeIDDirResponse(rsp)
}

// GetVolumecontentVolumeIDFileWithResponse request returning *GetVolumecontentVolumeIDFileResponse
func (c *ClientWithResponses) GetVolumecontentVolumeIDFileWithResponse(ctx context.Context, volumeID VolumeID, params *GetVolumecontentVolumeIDFileParams, reqEditors ...RequestEditorFn) (*GetVolumecontentVolumeIDFileResponse, error) {
	rsp, err := c.GetVolumecontentVolumeIDFile(ctx, volumeID, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVolumecontentVolumeIDFileResponse(rsp)
}

// PutVolumecontentVolumeIDFileWithBodyWithResponse request with arbitrary body returning *PutVolumecontentVolumeIDFileResponse
func (c *ClientWithResponses) PutVolumecontentVolumeIDFileWithBodyWithResponse(ctx context.Context, volumeID VolumeID, params *PutVolumecontentVolumeIDFileParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutVolumecontentVolumeIDFileResponse, error) {
	rsp, err := c.PutVolumecontentVolumeIDFileWithBody(ctx, volumeID, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutVolumecontentVolumeIDFileResponse(rsp)
}

// DeleteVolumecontentVolumeIDPathWithResponse request returning *DeleteVolumecontentVolumeIDPathResponse
func (c *ClientWithResponses) DeleteVolumecontentVolumeIDPathWithResponse(ctx context.Context, volumeID VolumeID, params *DeleteVolumecontentVolumeIDPathParams, reqEditors ...RequestEditorFn) (*DeleteVolumecontentVolumeIDPathResponse, error) {
	rsp, err := c.DeleteVolumecontentVolumeIDPath(ctx, volumeID, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteVolumecontentVolumeIDPathResponse(rsp)
}

// GetVolumecontentVolumeIDPathWithResponse request returning *GetVolumecontentVolumeIDPathResponse
func (c *ClientWithResponses) GetVolumecontentVolumeIDPathWithResponse(ctx context.Context, volumeID VolumeID, params *GetVolumecontentVolumeIDPathParams, reqEditors ...RequestEditorFn) (*GetVolumecontentVolumeIDPathResponse, error) {
	rsp, err := c.GetVolumecontentVolumeIDPath(ctx, volumeID, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVolumecontentVolumeIDPathResponse(rsp)
}

// PatchVolumecontentVolumeIDPathWithBodyWithResponse request with arbitrary body returning *PatchVolumecontentVolumeIDPathResponse
func (c *ClientWithResponses) PatchVolumecontentVolumeIDPathWithBodyWithResponse(ctx context.Context, volumeID VolumeID, params *PatchVolumecontentVolumeIDPathParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchVolumecontentVolumeIDPathResponse, error) {
	rsp, err := c.PatchVolumecontentVolumeIDPathWithBody(ctx, volumeID, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchVolumecontentVolumeIDPathResponse(rsp)
}

func (c *ClientWithResponses) PatchVolumecontentVolumeIDPathWithResponse(ctx context.Context, volumeID VolumeID, params *PatchVolumecontentVolumeIDPathParams, body PatchVolumecontentVolumeIDPathJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchVolumecontentVolumeIDPathResponse, error) {
	rsp, err := c.PatchVolumecontentVolumeIDPath(ctx, volumeID, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchVolumecontentVolumeIDPathResponse(rsp)
}

// ParseGetVolumecontentVolumeIDDirResponse parses an HTTP response from a GetVolumecontentVolumeIDDirWithResponse call
func ParseGetVolumecontentVolumeIDDirResponse(rsp *http.Response) (*GetVolumecontentVolumeIDDirResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVolumecontentVolumeIDDirResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VolumeDirectoryListing
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostVolumecontentVolumeIDDirResponse parses an HTTP response from a PostVolumecontentVolumeIDDirWithResponse call
func ParsePostVolumecontentVolumeIDDirResponse(rsp *http.Response) (*PostVolumecontentVolumeIDDirResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostVolumecontentVolumeIDDirResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest VolumeEntryStat
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetVolumecontentVolumeIDFileResponse parses an HTTP response from a GetVolumecontentVolumeIDFileWithResponse call
func ParseGetVolumecontentVolumeIDFileResponse(rsp *http.Response) (*GetVolumecontentVolumeIDFileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVolumecontentVolumeIDFileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutVolumecontentVolumeIDFileResponse parses an HTTP response from a PutVolumecontentVolumeIDFileWithResponse call
func ParsePutVolumecontentVolumeIDFileResponse(rsp *http.Response) (*PutVolumecontentVolumeIDFileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutVolumecontentVolumeIDFileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest VolumeEntryStat
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteVolumecontentVolumeIDPathResponse parses an HTTP response from a DeleteVolumecontentVolumeIDPathWithResponse call
func ParseDeleteVolumecontentVolumeIDPathResponse(rsp *http.Response) (*DeleteVolumecontentVolumeIDPathResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteVolumecontentVolumeIDPathResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetVolumecontentVolumeIDPathResponse parses an HTTP response from a GetVolumecontentVolumeIDPathWithResponse call
func ParseGetVolumecontentVolumeIDPathResponse(rsp *http.Response) (*GetVolumecontentVolumeIDPathResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVolumecontentVolumeIDPathResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VolumeEntryStat
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePatchVolumecontentVolumeIDPathResponse parses an HTTP response from a PatchVolumecontentVolumeIDPathWithResponse call
func ParsePatchVolumecontentVolumeIDPathResponse(rsp *http.Response) (*PatchVolumecontentVolumeIDPathResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchVolumecontentVolumeIDPathResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VolumeEntryStat
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
